development:
  adapter: mysql
  database: rss_development
  username: root
  password:

test:
  adapter: mysql
  database: rss_test
  username: root
  password:

production:
  adapter: mysql
  database: rss_production
  username: deploy
  password: tr4v3l
  host: localhost
